### ISSUE TITLE
Feature request - ASREPRoast

### ISSUE THREAD

**Issue by Lexus89** [skelsec/kerberoast#1]
As requested, I placed this request here instead of at the PyKerberos repo. It would be a great addition to also have an implementation of AsRepRoast with a userlist & bruteforce of accounts:

http://www.harmj0y.net/blog/activedirectory/roasting-as-reps/

**Comment by skelsec** [comment]
I have secretly started working on it :P

**Comment by skelsec** [comment]
Done.
