### ISSUE TITLE
Solution for msldap.core error

### ISSUE THREAD

**Issue by intrd** [skelsec/kerberoast#4]
If you are struggling with this error..

```
Traceback (most recent call last):
  File "/usr/local/bin/kerberoast", line 5, in <module>
    from kerberoast.kerberoast import run
  File "/usr/local/lib/python3.7/dist-packages/kerberoast/kerberoast.py", line 7, in <module>
    from msldap.core import *
ModuleNotFoundError: No module named 'msldap.core'
```

just do..
```
python3 -m pip uninstall msldap
python3 -m pip install msldap==0.1.0
```

Permanent fix suggestion:
change `msldap>=0.0.3` to `msldap==0.1.0` on requeriments.txt

**Comment by skelsec** [comment]
Ohh dear! I forgot to update this package.
Will fix asap

Thx for mentioning

**Comment by skelsec** [comment]
Okay, I think it's now fixed in the new version. Please confirm and close.

**Comment by v-p-b** [comment]
Dependencies seem to lag behind you other libs, I think it'd be safer to specify exact versions. 

Also, a little dependency hell is forming around minikerberos and asyauth...

**Comment by skelsec** [comment]
I'm a little worried about using fixed versions, as it would create major issues around distros who are packaging my tools (see the versions of my projects in Kali and BlackArch). 
The reason these issues exist in this project is that I keep forgetting about updating this :( Will update it soon.
In the meantime: what dependency hell are you referring to? Is it about this one or in general?

**Comment by v-p-b** [comment]
Minikerberos needed dowgrading too in my case, that resulted in this warning:

```
% pip install 'minikerberos==0.2.10'
Collecting minikerberos==0.2.10
  Using cached minikerberos-0.2.10-py3-none-any.whl (107 kB)
Requirement already satisfied: asysocks>=0.0.11 in ./lib/python3.8/site-packages (from minikerberos==0.2.10) (0.2.2)
Requirement already satisfied: asn1crypto>=1.3.0 in ./lib/python3.8/site-packages (from minikerberos==0.2.10) (1.5.1)
ERROR: asyauth 0.0.3 has requirement minikerberos>=0.3.1, but you'll have minikerberos 0.2.10 which is incompatible.
```
This tells me that these dependencies should be updated in a lockstep.

**Comment by skelsec** [comment]
2 weeks ago all my projects underwent a major version change with the introduction of unicomms and asyauth sadly this involved API changes that are not compatible with previous versions.  
I tried to update the versions of all projects, this one went under the radar. Rest assured, this will be also updated.

**Comment by skelsec** [comment]
new release version 0.2.0 is up, please try it and let me know if something is not looking good

**Comment by v-p-b** [comment]
Look good, thanks for the fast response!
